### PR TITLE
Resolve uppercase table names.

### LINKED ISSUE #78: DB table names should be all lowercase
In PostgreSQL, if table names are not defined in all lowercase, you need to enclose the table names with quote when referencing the table name in SQL statements (ie., select \* from "Users").  Otherwise, you'll get `"ERROR: relation "xxx" does not exist" error.`

Enclosing table name with quotes can be a real pain, especially when you're debugging in psql or pgAdmin.  Please change the name of our tables in all lowercase.

### PR DESCRIPTION
**Pull request by nataliemeurer**
Resolve #78.

### CODE REVIEW

File: server/database/dbSchema.js [hunk 1]
```diff
@@ -8,56 +8,57 @@ var sequelize = new Sequelize(dbCreds.database, dbCreds.username, dbCreds.passwo
 var db = {}; // stores all methods
 
 // Location table schema
-var Locations = sequelize.define('Locations', {
```
Comment (ryojiosawa) [inline server/database/dbSchema.js:11]: @kmeurer - I don't think this will fix the issue with Postgres case sensitivity issue.  I think we need to change the table name from 'Location' to 'location'.

**Comment by ryojiosawa** [comment]
:+1:
